name: Dockerimage

on:
  push:
    branches: 
      - master

jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |  
        docker login -u $HUB_NAME -p $HUB_KEY
        
        docker build . --pull --no-cache --file Dockerfile --tag zocker160/sheepit-client:latest
        docker build . --pull --no-cache --file Dockerfile.cuda11 --tag zocker160/sheepit-client:nvidia
        docker build . --pull --no-cache --file Dockerfile.cuda10 --tag zocker160/sheepit-client:cuda10
        
        docker push zocker160/sheepit-client:latest
        docker push zocker160/sheepit-client:nvidia
        docker push zocker160/sheepit-client:cuda10
        
